# Generated by Django 5.1.6 on 2025-03-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_user_created_at_user_modified_at_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
    ]
