# Generated by Django 5.1.6 on 2025-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_profile_company_remove_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
