# Generated by Django 5.1.6 on 2025-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="modified_at",
        ),
    ]
