# Generated by Django 5.1.6 on 2025-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinventory",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=500000.0, max_digits=20
            ),
        ),
    ]
